services:
  - type: web
    name: growth-grub
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: EMAILJS_SERVICE_ID
        sync: false
      - key: EMAILJS_TEMPLATE_ID
        sync: false
      - key: EMAILJS_PUBLIC_KEY
        sync: false
      - key: GOOGLE_SHEETS_PROJECT_ID
        sync: false
      - key: GOOGLE_SHEETS_PRIVATE_KEY_ID
        sync: false
      - key: GOOGLE_SHEETS_PRIVATE_KEY
        sync: false
      - key: GOOGLE_SHEETS_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_SHEETS_CLIENT_ID
        sync: false
      - key: GOOGLE_SHEETS_SPREADSHEET_ID
        sync: false 